#include <stdio.h>
#include <string.h>

/*
 * Unused routine to parse MCS files.  This has been tested on a basic MCS file generated
 * by iMPACT.  This may be useful if we want to use mutliboot images generated by iMPACT
 * at a later date.
 */


int parseMVS(FILE *inputFile, unsigned char *flashMemory, unsigned int flashMemoryMax, unsigned int *flashDataLen) {

	char line[1024];
	unsigned int byteCount, recAddr, recType, highAddr;
	unsigned int i, dataByte;

	*flashDataLen = 0;

	while (!feof(inputFile)) {

		memset(line, 0, sizeof(line));

		if (!fgets(line, sizeof(line), inputFile)) {
			break;
		}

		if (line[strlen(line) - 1] == '\n') {
			line[strlen(line) - 1] = 0;
		}
		if (line[strlen(line) - 1] == '\r') {
			line[strlen(line) - 1] = 0;
		}

		if (!line[0] == ':') {
			fprintf(stderr, "Invalid line in file: %s\n", line);
			return 1;
		}

		if (sscanf(line+1, "%2X%4X%2X", &byteCount, &recAddr, &recType) != 3) {
			fprintf(stderr, "Invalid line in file: %s\n", line);
			return 1;
		}

		if (recType == 0) {

			if (strlen(line) != 1+8+2+(byteCount*2)) {
				fprintf(stderr, "Invalid line length: %i %s\n", (1+8+2+byteCount), line);
				return 1;
			}

			for (i = 0; i < byteCount; i++) {

				if (sscanf(line+1+8+(i*2), "%2X", &dataByte) != 1) {
					fprintf(stderr, "Error while reading byte in line: %s\n", line);
					return 1;
				}

				if (highAddr + recAddr + i >= flashMemoryMax) {
					fprintf(stderr, "Address out of range in line: %s\n", line);
					return 1;
				}

				flashMemory[highAddr + recAddr + i] = dataByte & 0xFF;

			}

			if (highAddr + recAddr + byteCount > *flashDataLen)
				*flashDataLen = highAddr + recAddr + byteCount;

		}
		else if (recType == 1) {
			break;
		}
		else if (recType == 4) {

			if (strlen(line) != 1+8+2+(byteCount*2)) {
				fprintf(stderr, "Invalid line length: %i %s\n", (1+8+2+byteCount), line);
				return 1;
			}

			if (byteCount != 2) {
				fprintf(stderr, "Invalid byte count for linear address record in line: %s\n", line);
				return 1;
			}

			if (sscanf(line+1+8, "%4X", &recAddr) != 1) {
				fprintf(stderr, "Invalid line in file: %s\n", line);
				return 1;
			}

			highAddr = recAddr << 16;

		}
		else {
			fprintf(stderr, "Invalid record type in line: %s\n", line);
			return 1;
		}

	}

	return 0;

}
